lifting-bits/rellic

rellic/AST/CXXToCDecl.cpp
tests/pair.hpp

Improves overall handling of templates

---

CMakeLists.txt
README.md

Adds Z3 as an external CMake project

---

rellic/AST/ExprCombine.cpp
rellic/AST/IRToASTVisitor.cpp
scripts/travis.sh

Fixes build issues due to LLVM API changes

---

rellic/AST/GenerateAST.cpp

Adds forward declarations of functions

---

rellic/AST/ExprCombine.cpp
rellic/AST/IRToASTVisitor.cpp
rellic/AST/Util.cpp
rellic/AST/Util.h
rellic/AST/Z3ConvVisitor.cpp

Various small fixes that were uncovered by trying to roundtrip mcsema bitcode.

Fixes to mcsema bitcode syntax errors

---

.gitignore
.travis.yml
CMakeLists.txt
Dockerfile
README.md
cmake/modules/FindZ3.cmake
scripts/build.sh
scripts/docker-decomp-entrypoint.sh
scripts/roundtrip.py
scripts/travis.sh

* Base image is cxx-common
* Build Z3 in Dockerfile
* Create a build-only option to avoid downloading cxx-common
* Migrate to cmake -G Ninja versus makefiles

Use cxx-common docker base

---

.dockerignore
Dockerfile
cmake/git_watcher.cmake
rellic/CMakeLists.txt
rellic/Version/CMakeLists.txt
rellic/Version/Version.cpp.in
rellic/Version/Version.h
tools/decomp/Decomp.cpp
tools/headergen/HeaderGen.cpp

Emit detailed information when using `--version`

Output detailed version information

---

.github/workflows/ci.yml
README.md
rellic/AST/CXXToCDecl.cpp
rellic/AST/CXXToCDecl.h
rellic/AST/Compat/ASTContext.cpp
rellic/AST/Compat/ASTContext.h
rellic/AST/Compat/Expr.cpp
rellic/AST/Compat/Mangle.cpp
rellic/AST/Compat/Mangle.h
rellic/AST/Compat/Stmt.cpp
rellic/AST/CondBasedRefine.h
rellic/AST/DeadStmtElim.h
rellic/AST/ExprCombine.h
rellic/AST/GenerateAST.cpp
rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/LoopRefine.h
rellic/AST/NestedCondProp.h
rellic/AST/NestedScopeCombiner.h
rellic/AST/ReachBasedRefine.h
rellic/AST/Util.h
rellic/AST/Z3CondSimplify.h
rellic/AST/Z3ConvVisitor.cpp
rellic/CMakeLists.txt
scripts/docker-decomp-entrypoint.sh
tests/tools/decomp/branch.c
tools/decomp/Decomp.cpp
tools/headergen/HeaderGen.cpp

Fixes support for LLVM 10 and 11

---

rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/Z3CondSimplify.cpp
rellic/AST/Z3ConvVisitor.cpp
tools/decomp/Decomp.cpp

Misc fixes, adds LLVM IR and Z3 operation handlers and `disable_z3` flag

---

README.md
scripts/build.sh
scripts/build_with_vcpkg.sh

Try to fix issues brought up in #89 
* Does not try to redownload the pre-built library tar ball
closes #89

Update README and update build script for vcpkg

---

tools/decomp/Decomp.cpp

Demotes llvm::PHINodes to stack memory before decompiling. Resolves #102 .

Adds `--remove_phi_nodes` option

---

rellic/AST/Util.cpp

Fixes translation of LLVM i128 type to C

---

rellic/AST/Util.cpp
tests/tools/decomp/issue_123_uint128_t.c

Adds a regression test for LLVM i128 type translation to C

---

rellic/AST/Z3ConvVisitor.cpp
rellic/AST/Z3ConvVisitor.h
tests/tools/decomp/issue_126_bool2bv.c

Adds Z3 conversions from bool to bitvector sorts

---

rellic/AST/IRToASTVisitor.cpp
tests/tools/decomp/issue_127_uint128_t_lit.c

Adds handling of 128-bit integer literals

---

.github/workflows/ci.yml
scripts/run-on-anghabench.sh
scripts/test-angha-1k.sh

* Make angha tests do recompilation
* Currently only informational; will not block a merge

Update Rellic tests to do recompilation

---

rellic/AST/ExprCombine.cpp

Adds rule to fold  `expr[0].field` to `arr->field`

---

.github/workflows/anghabench-cron-jobs.yml
scripts/run-on-anghabench.sh

* Save decompilation results from cron job run
* Save recompilation results from cron job run
* Msg links into Slack

Save CI results in DO Spaces

---

rellic/AST/ASTBuilder.cpp
rellic/AST/ASTBuilder.h

Adds precedence handling to CreateCall

---

CMakeLists.txt
README.md

- add note on required recursive clone
- allow to disable test build

Fix minor issues with build

---

.github/workflows/ci.yml
CMakePresets.json
scripts/build-preset.sh

* Create a CMakePresets build
* Test it in CI

Attempt to use CMakePresets to build

---

lib/AST/Util.cpp

Fix iterator invalidation

---

include/rellic/AST/ASTBuilder.h
include/rellic/AST/IRToASTVisitor.h
lib/AST/ASTBuilder.cpp
lib/AST/IRToASTVisitor.cpp

Convert intrinsics to builtin calls

---

include/rellic/AST/ASTBuilder.h
include/rellic/AST/IRToASTVisitor.h
include/rellic/BC/Util.h
lib/AST/ASTBuilder.cpp
lib/AST/IRToASTVisitor.cpp
lib/AST/Util.cpp
lib/BC/Util.cpp
lib/Decompiler.cpp

Adds IR passes to convert `store`s of array types and functions with array arguments. Also implements `insertvalue`.

Fix aggregate type handling

---

tools/xref/Xref.cpp
tools/xref/www/index.html

Adds a features where the server can be made to load local bitcode files instead of having to upload them.
**SECURITY ISSUE**: this allows the user to potentially read any file the server program has access to. Not that it was any safer before, this interface is really not supposed to be exposed on the internet anyway.

Allow loading bitcode files from server

---

CMakePresets.json
scripts/build-preset.sh

* Support for building against an ASAN cxx-common

Add CMakePresets support for building with ASAN

---

include/rellic/AST/Util.h
lib/AST/IRToASTVisitor.cpp
scripts/decompile.py
scripts/roundtrip.py

Angha is still using the `--remove-phi-nodes` flag

Handle Phi nodes directly

---

tools/CMakeLists.txt

These should have been included in #246, but I forgor 💀

Install additional files for `rellic-xref`

---

include/rellic/AST/ASTBuilder.h
lib/AST/ASTBuilder.cpp
lib/AST/IRToASTVisitor.cpp
tests/tools/decomp/fcmp.c

Provide implementation for various float ops

---

include/rellic/AST/NestedCondProp.h
include/rellic/AST/Util.h
lib/AST/LoopRefine.cpp
lib/AST/NestedCondProp.cpp
lib/AST/Util.cpp

Also improves the amount of propagated conditions by `NestedCondProp`

Fixes #261

---

lib/CMakeLists.txt
unittests/AST/Z3ConvVisitor.cpp
unittests/CMakeLists.txt

CMake fix and include z3 header where z3 is used

Fix Z3 dependency usage

---

lib/AST/IRToASTVisitor.cpp
tools/decomp/Decomp.cpp
tools/repl/Repl.cpp
tools/xref/Xref.cpp

Should fix the crashes in Anvill-produced bitcode
cc @tetsuo-cpp

Fix crashes from AMP challenges

---

lib/AST/IRToASTVisitor.cpp

Fixes crash on trailofbits/IRENE#80

Fixup function type in call instructions

---

include/rellic/AST/ASTBuilder.h
lib/AST/ASTBuilder.cpp
lib/AST/IRToASTVisitor.cpp

NaN would also be kinda viable

Replace undef constant floats with 0
