lifting-bits/rellic

rellic/AST/GenerateAST.cpp
tests/issue_4.c

Function body ASTs were incorrectly generated when the input had
multiple function definitions. Previously generated function bodies
were assigned to subsequently generated functions. Which caused a
SIGSEGV in the later AST refinement passes.

Fixes issue #4

---

rellic/AST/CondBasedRefine.cpp
rellic/AST/CondBasedRefine.h
rellic/AST/DeadStmtElim.cpp
rellic/AST/DeadStmtElim.h
rellic/AST/GenerateAST.cpp
rellic/AST/GenerateAST.h
rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/LoopRefine.cpp
rellic/AST/LoopRefine.h
rellic/AST/NestedCondProp.cpp
rellic/AST/NestedCondProp.h
rellic/AST/NestedScopeCombiner.cpp
rellic/AST/NestedScopeCombiner.h
rellic/AST/Util.cpp
rellic/AST/Util.h
rellic/AST/Z3CondSimplify.cpp
rellic/AST/Z3CondSimplify.h
tools/decomp/Decomp.cpp

Replaces clang::CompilerInstance with clang::ASTContext in AST visitor constructors.

Minor code improvements

---

README.md
rellic/AST/CXXToCDecl.cpp
rellic/AST/CXXToCDecl.h
tools/headergen/HeaderGen.cpp

This PR adds handling of pointer and reference types. Also refactors `CXXToCDeclVisitor` to work in pre-order (which seems to be more in line of how clang intends the AST to be created) and splits it's visitor methods into more manageable chunks.
Closes #18 
Previously:
```C++
struct _ZTSSt4pairIiiE {
int first;
int second;
};
void _ZNSt4pairIiiEC1Ev(struct _ZTSSt4pairIiiE *this);
void _ZNSt4pairIiiEC1ERKiS2_(struct _ZTSSt4pairIiiE *this, const int &__a, const int &__b);
struct _ZTS7MyClass {
struct _ZTSSt4pairIiiE my_pair;
};
struct _ZTSSt4pairIiiE _ZN7MyClass8MyMethodESt4pairIiiE(struct _ZTS7MyClass *this, struct _ZTSSt4pairIiiE pair);
```
Currently:
```C++
struct _ZTSSt4pairIiiE {
int first;
int second;
};
void _ZNSt4pairIiiEC1Ev(struct _ZTSSt4pairIiiE *this);
void …
```

Handling of reference and pointer types

---

rellic/AST/ExprCombine.cpp
rellic/AST/ExprCombine.h
rellic/AST/GenerateAST.cpp
rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/Util.cpp
rellic/AST/Util.h
rellic/AST/Z3ConvVisitor.cpp
rellic/AST/Z3ConvVisitor.h

Resolves #29
Adds initial handling of aggregate LLVM types and NULL pointer constants. This includes translation of GEP instructions with aggregate type operands to the corresponding C operations (array subscript and member access expressions).
Subsequently adds Z3 simplification and rule-based simplification of expressions with above mentioned operands.

Translation and simplification of aggregate LLVM types

---

rellic/AST/GenerateAST.cpp

This should resolve any outstanding build errors from #30

Reimplements llvm::Region::getNameStr() as GetRegionNameStr()

---

rellic/AST/ExprCombine.cpp
rellic/AST/GenerateAST.cpp
rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/Util.cpp
rellic/AST/Util.h
rellic/AST/Z3ConvVisitor.cpp
rellic/AST/Z3ConvVisitor.h
tests/array_swap.c
tests/bitops.c
tests/cast.c
tests/funcptr.c
tests/init_list.c
tests/inttoptr.c
tests/nested_struct.c
tests/nullptr.c
tests/ret0.c
tests/struct.c
tests/struct_swap.c
tests/trunc.c
tests/zeroinit.c
tests/zext.c
tools/decomp/Decomp.cpp

Adds various instruction handlers to both `IR->AST` and `Z3 <-> C` conversion passes, fixes issues with old code that bubbled up along the way, does some minor refactors. End result is that bitcode produced from [McSema](https://github.com/lifting-bits/mcsema) produces C.
Now to set expectations right, the C has syntax errors and is unlikely to work even when those are fixed. The purpose of passing McSema bitcode was to stress test rellic. Not to produce working C from it. Maybe sometime in the future rellic will be able to produce re-compilable bitcode from McSema.
resolves #34

McSema bitcode stress test

---

README.md
scripts/travis.sh

`unzip` is used when extracting the downloaded Z3 package.
I found this by trying to create a Docker image and found that the unzip
command was missing.
I also added it to the `scripts/travis.sh` script, in case the script was ever used in a CI environment that didn't have unzip preinstalled.

Add unzip Ubuntu build dependency

---

rellic/AST/IRToASTVisitor.cpp
tests/tools/decomp/binops.c

- `Or` and `Mul` opcodes
- Added print so the missing opcode is known in the error
Note that division is still missing, I am not certain on how to handle both unsigned or signed division (or does it even matter, I may just lift it as the `clang::BO_Div`?)

Add more missing BinOp

---

rellic/AST/GenerateAST.cpp

This is hopefully a temporary "fix" until I learn more about exceptions and figure out how to really handle them in the context of rellic.
closes #49

Adds a friendlier error when encountering exception related terminators

---

rellic/AST/Z3ConvVisitor.cpp
tools/decomp/Decomp.cpp

closes #50 and adds a few nicer errors.

Adds elim-and before tseitin-cnf to get rid of leftover aux vars

---

rellic/AST/CondBasedRefine.cpp
rellic/AST/CondBasedRefine.h
rellic/AST/NestedCondProp.cpp
rellic/AST/ReachBasedRefine.cpp
rellic/AST/ReachBasedRefine.h
rellic/CMakeLists.txt
tests/tools/decomp/assert.c
tests/tools/decomp/binops.c
tools/decomp/Decomp.cpp

As subjects suggests and resolves #60. Reachability-based refinement constructs `else-if` cascades when no more `if-then-else` condition-based refinement can be done.

Adds reachability-based refinement from No More Gotos

---

rellic/AST/GenerateAST.cpp
rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/Util.cpp
rellic/AST/Util.h
scripts/roundtrip.py

Fixes the following
Input:
```llvm
; ModuleID = 'ret666.json'
source_filename = "ret666.json"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu-elf"
; Function Attrs: noinline
define i64 @f() local_unnamed_addr #0 {
ret i64 333
}
; Function Attrs: noinline
define i32 @main(i32, i8**, i8**) local_unnamed_addr #0 {
%4 = call i64 @f()
%.sroa.271.2216.extract.trunc = trunc i64 %4 to i32
%5 = add i32 333, %.sroa.271.2216.extract.trunc
ret i32 %5
}
attributes #0 = { noinline }
```
Before (master):
```C
unsigned long f();
unsigned int main(unsigned int arg0, unsigned char **arg1, unsigned char **arg2);
unsigned long f() {
return 333UL;
}
unsigned int main(unsigned int arg0, unsigned char **arg1, unsigned char **arg2) {
f();
(unsigned int)(f());
333U …
```

Duplicate calls to functions with possible side-effects

---

cmake/settings.cmake

Use `-ggdb` as the preferred debug flag.

Update preferred debug flags

---

rellic/AST/IRToASTVisitor.cpp
rellic/AST/Z3ConvVisitor.cpp
tests/tools/decomp/short.c

Basically for a 16-bit `42` literal we emit `(unsigned short) 42U`. Resolves #104 .

Adds proper handling of 16-bit integer literals

---

rellic/AST/IRToASTVisitor.cpp

* Try to catch some missing cases for Value derivatives (could be more thorough?)
* Ouput the LLVMThingToString on FATAL

More granular errors from IRToASTVisitor

---

rellic/AST/IRToASTVisitor.cpp
rellic/AST/IRToASTVisitor.h
rellic/AST/Util.cpp
rellic/BC/Compat/IntrinsicInst.h
rellic/BC/Util.cpp
rellic/BC/Util.h

* Skip annotation intrinsic functions
* Skip global variables that go into metadata like llvm.used

Skip annotation intrinsics when translating to C

---

rellic/AST/Z3ConvVisitor.cpp

Fixes a typo in IsSignExt()

---

unittests/AST/ASTBuilder.cpp

This is an error on Windows:
```
rellic/unittests/AST/ASTBuilder.cpp(64,21): error : call to constructor of 'llvm::APInt' is ambiguous
.../include/llvm/ADT/APInt.h(277,3): message : candidate constructor
.../include/llvm/ADT/APInt.h(304,3): message : candidate constructor
```

Fix constructor ambiguity error llvm::APInt in tests LLVM 11

---

rellic/AST/Z3CondSimplify.cpp
rellic/AST/Z3ConvVisitor.cpp
tools/decomp/Decomp.cpp

The `tseitin-cnf` tactic was used to help with the final simplification of conditions, but in some cases it introduces auxiliary variables that don't have an equivalent in C.
Also adds `Z3_OP_BAND` and `Z3_OP_ZERO_EXT` handlers to `Z3ConvVisitor`

Disables Tseitin-CNF and adds minor z3 operation handlers

---

README.md
scripts/requirements.txt
scripts/test-angha-1k.sh

Uses /usr/bin/env to lookup bash executable because macOS ships with old
version at /bin/bash
Updated README with Python requirements

Support angha testing on macOS

---

rellic/AST/ASTBuilder.cpp
rellic/AST/ASTBuilder.h
rellic/AST/IRToASTVisitor.cpp
unittests/AST/ASTBuilder.cpp

Fix handling of `undef` integer values
This was the source of a segfault due to a failed cast.

Fix handling of undef integer values.

---

rellic/AST/IRToASTVisitor.cpp

Adds a default handler for addrspace casts to get at least some output for bitcode that uses these. Filed issue #160 to track a more comprehensive solution.

Add a default handler for addrspace casts

---

rellic/AST/ExprCombine.cpp
rellic/AST/Z3CondSimplify.cpp
rellic/AST/Z3CondSimplify.h
rellic/AST/Z3ConvVisitor.cpp

Eliminates explicit widening integer cast expressions whose effect is negated by a subsequent narrowing cast, i.e:
```C
(unsigned)(long long)(int)expr
```
to
```C
(int)(char)expr
```
also rewrites ternary conditionals of form
```C
cond ? 1U : 0U
```
to
```C
cond
```

Adds rules for elimination of ternary conditionals and casts

---

README.md

From the commit message:
> The `doctest-dev` package available in Debian and Ubuntu repositories
was not recently listed in the README.md build instructions for Linux,
but is required. I've added it to the example, as well as switched the
`apt-get` invocations to the canonically-preferred `apt` tool.
I'm a first-time contributor to this project, so I don't know if anyone has
strong opinions on the `apt-get` vs `apt` thing; since the example seems
more oriented towards interactive usage rather than being in a script, I
figured the change might be an apt choice :)
If people *do* think it's unnecessary, I'm more than happy to undo the change.

Fix missing dependencies in Linux build example

---

include/rellic/AST/IRToASTVisitor.h
include/rellic/AST/Util.h
lib/AST/ExprCombine.cpp
lib/AST/IRToASTVisitor.cpp
lib/AST/Util.cpp
lib/AST/Z3ConvVisitor.cpp

* Changes handling of `NullToPointer` casts to be the same as `IntegralToPointer` in C -> Z3 codegen
* Adds C codegen for `freeze` LLVM IR instruction
* Adds C codegen for `i128` LLVM IR constants

Misc fixes

---

lib/AST/LoopRefine.cpp

`LoopRefine` recognizes patterns like
```c
while(1) {
if(cond) {
break;
}
body;
}
```
and turns it into
```c
while(!cond) {
body;
}
```
Unfortunately it also discards the `else` branch of the `if` statement used for the loop refinements, which leads to incorrect results when multiple `if` statements have been merged into one by a previous pass like `ConditionBasedRefine`. This fixes that.

Fix issue with `LoopRefine`

---

include/rellic/AST/Util.h
lib/AST/NestedCondProp.cpp
lib/AST/Util.cpp
lib/AST/Z3ConvVisitor.cpp

Using Z3 to substitute expressions as a black box loses all provenance info contained inside.
Substituting C expressions directly avoids this.

Replace expressions in C AST instead of Z3 AST

---

include/rellic/AST/ASTPass.h
include/rellic/AST/CondBasedRefine.h
include/rellic/AST/DeadStmtElim.h
include/rellic/AST/ExprCombine.h
include/rellic/AST/GenerateAST.h
include/rellic/AST/IRToASTVisitor.h
include/rellic/AST/LocalDeclRenamer.h
include/rellic/AST/LoopRefine.h
include/rellic/AST/NestedCondProp.h
include/rellic/AST/NestedScopeCombine.h
include/rellic/AST/NormalizeCond.h
include/rellic/AST/ReachBasedRefine.h
include/rellic/AST/StructFieldRenamer.h
include/rellic/AST/TransformVisitor.h
include/rellic/AST/Z3CondSimplify.h
lib/AST/CondBasedRefine.cpp
lib/AST/DeadStmtElim.cpp
lib/AST/ExprCombine.cpp
lib/AST/GenerateAST.cpp
lib/AST/IRToASTVisitor.cpp
lib/AST/LocalDeclRenamer.cpp
lib/AST/LoopRefine.cpp
lib/AST/NestedCondProp.cpp
lib/AST/NestedScopeCombine.cpp
lib/AST/NormalizeCond.cpp
lib/AST/ReachBasedRefine.cpp
lib/AST/StructFieldRenamer.cpp
lib/AST/Z3CondSimplify.cpp
lib/Decompiler.cpp
tools/repl/Repl.cpp

Removes usage of the legacy LLVM pass managers.
Also introduces a new API for AST passes, which are designed to be interruptible and not own the data they manipulate, e.g. they don't take ownership of provenance info. This is to simplify management of resources in interactive settings.

Use new pass API

---

include/rellic/BC/Util.h
lib/AST/IRToASTVisitor.cpp
lib/BC/Util.cpp
lib/Decompiler.cpp

Patching the bitcode to remove array stores had the potential for creating invalid modules.
Handling the stores in the codegen phase fixes the issue.
(Sprinkled some validation after each IR pass for good measure)

Use different approach for handling array stores

---

tools/CMakeLists.txt

The old version breaks on the new OpenSSL version(s).
This dependency should be managed by cxx-common instead of the FetchContent call. I am adding the `cpp-httplib` port to cxx-common for the next release, at which point we can make the conversion to use `find_package`.
See https://github.com/lifting-bits/cxx-common/pull/935

Bump httplib to v0.10.6

---

include/rellic/AST/CondBasedRefine.h
include/rellic/AST/GenerateAST.h
include/rellic/AST/ReachBasedRefine.h
include/rellic/AST/Util.h
include/rellic/AST/Z3CondSimplify.h
include/rellic/Decompiler.h
lib/AST/CondBasedRefine.cpp
lib/AST/GenerateAST.cpp
lib/AST/ReachBasedRefine.cpp
lib/AST/Util.cpp
lib/AST/Z3CondSimplify.cpp
lib/Decompiler.cpp
tests/tools/decomp/nested_while.c

As suspected, computing reaching conditions via fixpoint is indeed necessary, but was not performed previously due to performance concerns. I've finally been able to find the right Z3 incantation to make conditions simplify enough to compute them sufficiently fast (on my machine at least).

Fix bug in reaching conditions generation

---

lib/AST/DebugInfoCollector.cpp

Fixes a bug where debug info for `struct` types would be ignored on `alloca` instructions

Fix `DebugInfoCollector` type inspection

---

lib/AST/ExprCombine.cpp
lib/AST/IRToASTVisitor.cpp

I noticed that the LLVM module dumps still featured pointer types even though they should be opaque.
I'm not sure what the deal is with that, but in the meantime I'm using the same trick they are using to print pointer types. As long as this works, it should be better than nothing. It's also trivial to roll back when/if time comes.

Use non opaque ptr type when available

---

lib/Decompiler.cpp
tools/headergen/HeaderGen.cpp
tools/repl/Repl.cpp
tools/xref/Xref.cpp

An interaction between #273 and #274 generated warnings for strings, which made tests fail

Fix pointer sign warnings in strings

---

lib/Decompiler.cpp
tools/headergen/HeaderGen.cpp
tools/repl/Repl.cpp
tools/xref/Xref.cpp

Fixes a bug that made `rellic-xref` crash when trying to dispose of old sessions

Fix session cleanup crashes

---

cmake/modules/FindZ3.cmake

should be Z3_BUILD_NUMBER instead of Z3_BUILD_VERSION
see: https://github.com/llvm/llvm-project/blob/dc07d2c91dfd7f14991d07ef1df5f1f0b19b306d/llvm/cmake/modules/FindZ3.cmake#L103

Fix typo when parsing z3 version from headers

---

include/rellic/AST/CondBasedRefine.h
include/rellic/AST/ReachBasedRefine.h
include/rellic/BC/Util.h
lib/AST/CondBasedRefine.cpp
lib/AST/IRToASTVisitor.cpp
lib/AST/ReachBasedRefine.cpp
lib/AST/Util.cpp
lib/BC/Util.cpp
lib/Decompiler.cpp
tools/xref/Xref.cpp

Rellic generates temporary variables for every load in order to maintain an SSA-like structure. This also produces a lot of temporary variables which are annoying to read.
The observation is that a temporary is needed for a `load` of an `alloca` only if a `store` occurred between the use of said `load` and the `load` itself.
E.g.
```llvm
%alloca = alloca ...
store sth, %alloca
%load = load %alloca
%foo = add %load, ... ; %load doesn't need a temporary variable
```
```llvm
%alloca = alloca ...
store sth, %alloca
%load = load %alloca
store sthelse, %alloca
%foo = add %load, ... ; %load needs a temporary variable
```

Limit amount of temporary variables

---

lib/AST/ASTBuilder.cpp

make errors go away with static_cast

c++20 does not like arithmetic between different enumeration types

---

.github/workflows/anghabench-after-build.yml
.github/workflows/anghabench-cron-jobs.yml
.github/workflows/ci.yml
.github/workflows/diff_tests.yml
scripts/build.sh

* Use AWS instead of DO for CI Runners

Attempt to use AWS CI Runners instead of DO for CI

---

include/rellic/AST/DecompilationContext.h
include/rellic/AST/TypeProvider.h
include/rellic/AST/Util.h
include/rellic/Decompiler.h
lib/AST/GenerateAST.cpp
lib/AST/IRToASTVisitor.cpp
lib/AST/TypeProvider.cpp
lib/AST/Util.cpp
lib/CMakeLists.txt
lib/Decompiler.cpp
tools/decomp/Decomp.cpp

Supersedes #302
Allows mechanisms to override the default LLVM type-to-Clang type conversion for functions and global variables

Type providers

---

README.md

Add examples and blog post links

---

README.md

Without this line the image built just fine, but when trying to run it failed with `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory` error. I believe this parameter forces it to be build for the selected architecture so it is runnable under other archs.
Pretty sure this wont break building docker in Linux, but I haven't tested it.

Make built docker image runnable on Apple Silicon
